import { useEffect, useMemo, useState } from "react";
import { Chart, Detail, Empty, Kpi, Layout, RecordsTable, metrics } from "./components";
import { analyze, decide, health, insights } from "./services/api";
import type { FeedbackRecord, Insights } from "./types";
import { categoryKey, countBy, priorityOrder, severityOrder, text } from "./utils";

type Page = "overview" | "decision-analytics" | "feedback-details" | "department-performance";
const readPage = (): Page => (["overview","decision-analytics","feedback-details","department-performance"].includes(location.hash.slice(1)) ? location.hash.slice(1) as Page : "overview");

export default function App() {
  const [page, setPage] = useState<Page>(readPage); const [rows, setRows] = useState<FeedbackRecord[]>([]);
  const [online, setOnline] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [selected, setSelected] = useState<FeedbackRecord>();
  const [datasetInsights, setDatasetInsights] = useState<Insights>(); const [updated, setUpdated] = useState("");
  useEffect(() => { const onHash = () => setPage(readPage()); addEventListener("hashchange", onHash); health().then(setOnline); return () => removeEventListener("hashchange", onHash); }, []);
  const navigate = (next: string) => { location.hash = next; };
  const upload = async (file: File) => { setLoading(true); setError(""); setDatasetInsights(undefined); try { const analyzed = await analyze(file); const enriched: FeedbackRecord[] = []; for (const record of analyzed) enriched.push(await decide(record)); setRows(enriched); setUpdated(new Date().toLocaleString()); setDatasetInsights(await insights(enriched)); } catch (e) { setRows([]); setError(e instanceof Error ? e.message : "Unable to load data from backend"); } finally { setLoading(false); } };
  const data = useMemo(() => metrics(rows), [rows]);
  return <Layout path={page} onNavigate={navigate} online={online} hasData={rows.length > 0} onUpload={upload}>
    {loading && <div className="notice">Loading and enriching records from the backend…</div>}
    {error && <div className="error">{error}</div>}
    {!loading && !rows.length && <div className="welcome card"><div><p className="eyebrow">START HERE</p><h2>No feedback loaded</h2><p>Upload CSV, XLSX, or XLSM data. The existing backend will analyze and classify every record.</p></div></div>}
    {rows.length > 0 && page === "overview" && <Overview rows={rows} data={data} updated={updated} insights={datasetInsights}/>}
    {rows.length > 0 && page === "decision-analytics" && <DecisionAnalytics rows={rows} data={data} insights={datasetInsights}/>}
    {rows.length > 0 && page === "feedback-details" && <FeedbackDetails rows={rows} onSelect={setSelected}/>}
    {rows.length > 0 && page === "department-performance" && <DepartmentPerformance rows={rows} data={data} />}
    {selected && <Detail row={selected} close={()=>setSelected(undefined)}/>}
  </Layout>;
}

function Overview({ rows, data, updated, insights }: { rows: FeedbackRecord[]; data: ReturnType<typeof metrics>; updated: string; insights?: Insights }) {
  return <><div className="updated">Last fetched: {updated || "Not available from backend"}</div><div className="kpis"><Kpi label="Total feedbacks" value={rows.length}/><Kpi label="Valid rows" value={rows.length}/><Kpi label="Average priority score" value={data.avg.toFixed(2)} detail="P1 = 4, P4 = 1"/><Kpi label="Actions needed" value={data.actions} detail={`${data.high} high / critical`}/></div><div className="grid-2"><Chart title="Severity distribution" values={data.severity}/><Chart title="Priority distribution" values={data.priority}/><Chart title="Category / department" values={data.category}/><Chart title="Impact distribution" values={data.impact}/></div>{insights?.executive_summary && <InsightCard insights={insights}/>}</>;
}
function DecisionAnalytics({ rows, data, insights }: { rows: FeedbackRecord[]; data: ReturnType<typeof metrics>; insights?: Insights }) {
  const matrix = severityOrder.map(severity => ({ severity, values: Object.fromEntries(priorityOrder.map(priority => [priority, rows.filter(r=>text(r.severity)===severity && text(r.priority)===priority).length])) }));
  return <><div className="kpis"><Kpi label="Severity" value={Object.keys(data.severity).length}/><Kpi label="Priority" value={Object.keys(data.priority).length}/><Kpi label="Action" value={Object.keys(data.action).length}/></div><div className="grid-2"><Chart title="Action distribution" values={data.action}/><Chart title="Impact distribution" values={data.impact}/></div><section className="card"><h3>Severity vs priority</h3><div className="matrix">{matrix.map(item=><div key={item.severity}><b>{item.severity}</b>{priorityOrder.map(p=><span key={p}>{p}: {item.values[p]}</span>)}</div>)}</div></section>{insights?.executive_summary ? <InsightCard insights={insights}/> : <p className="muted">Dataset insight is not available from the backend.</p>}</>;
}
function InsightCard({ insights }: { insights: Insights }) { return <section className="card insight"><p className="eyebrow">DATASET INSIGHT · {insights.generation_status || "BACKEND"}</p><h3>{insights.executive_summary}</h3>{insights.key_insights?.slice(0,3).map((item,i)=><div className="insight-line" key={i}><b>{item.title || "Insight"}</b><span>{item.description || ""}</span></div>)}</section>; }
function FeedbackDetails({ rows, onSelect }: { rows: FeedbackRecord[]; onSelect: (r: FeedbackRecord)=>void }) { const [query,setQuery]=useState(""); const [filter,setFilter]=useState(""); const filtered = rows.filter(row => (!filter || [row.sentiment,row.severity,row.priority,row.action,categoryKey(row),row.impact_level].map(text).includes(filter)) && (!query || Object.values(row).some(value=>text(value).toLowerCase().includes(query.toLowerCase())))); return <><div className="filters"><input placeholder="Search ID, text, topic, keyword…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All values</option>{[...new Set(rows.flatMap(r=>[text(r.sentiment),text(r.severity),text(r.priority),text(r.action),categoryKey(r),text(r.impact_level)].filter(Boolean)))].sort().map(value=><option key={value}>{value}</option>)}</select><span>{filtered.length} of {rows.length} records</span></div><RecordsTable rows={filtered} onSelect={onSelect}/></>; }
function DepartmentPerformance({ rows, data }: { rows: FeedbackRecord[]; data: ReturnType<typeof metrics> }) { const groups = Object.entries(data.category).map(([name])=>{const subset=rows.filter(r=>categoryKey(r)===name);return {name,count:subset.length,avg:subset.length?subset.reduce((s,r)=>s+({P1:4,P2:3,P3:2,P4:1}[text(r.priority)]||0),0)/subset.length:0,critical:subset.filter(r=>["HIGH","CRITICAL"].includes(text(r.severity))).length,actions:subset.filter(r=>["CREATE_TASK","ESCALATE","IMMEDIATE_ESCALATION"].includes(text(r.action))).length};}).sort((a,b)=>b.count-a.count); const top = groups[0]; return <><div className="kpis"><Kpi label="Highest volume" value={top?.name || "Not available"}/><Kpi label="Highest average priority" value={[...groups].sort((a,b)=>b.avg-a.avg)[0]?.name || "Not available"}/><Kpi label="Most high / critical" value={[...groups].sort((a,b)=>b.critical-a.critical)[0]?.name || "Not available"}/><Kpi label="Most actions" value={[...groups].sort((a,b)=>b.actions-a.actions)[0]?.name || "Not available"}/></div><Chart title="Category / department volume" values={data.category}/><section className="card table-wrap"><h3>Category performance</h3><table><thead><tr><th>Category</th><th>Feedback count</th><th>Avg priority score</th><th>High / critical</th><th>Actions needed</th></tr></thead><tbody>{groups.map(item=><tr key={item.name}><td>{item.name}</td><td>{item.count}</td><td>{item.avg.toFixed(2)}</td><td>{item.critical}</td><td>{item.actions}</td></tr>)}</tbody></table>{!groups.length && <Empty/>}</section></>; }
