import type { ReactNode } from "react";
import type { FeedbackRecord } from "./types";
import { categoryKey, countBy, priorityScore, text } from "./utils";

export function Chart({ title, values, colors = ["#635bff","#21b6a8","#f2a93b","#ed6a5f","#8b5cf6"] }: { title: string; values: Record<string, number>; colors?: string[] }) {
  const total = Object.values(values).reduce((a,b) => a+b, 0) || 1; const entries = Object.entries(values);
  return <section className="card chart-card"><h3>{title}</h3><div className="bars">{entries.length ? entries.map(([name, value], i) => <div className="bar-row" key={name}><span>{name}</span><div className="bar-track"><i style={{ width: `${Math.max(3, value / total * 100)}%`, background: colors[i % colors.length] }} /></div><b>{value}</b></div>) : <Empty text="No data available" />}</div></section>;
}
export function Kpi({ label, value, detail }: { label: string; value: string | number; detail?: string }) { return <div className="card kpi"><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div>; }
export function Empty({ text = "No data available" }: { text?: string }) { return <div className="empty">{text}</div>; }
export function Layout({ path, onNavigate, online, children, hasData, onUpload }: { path: string; onNavigate: (p:string)=>void; online: boolean; children: ReactNode; hasData: boolean; onUpload: (f: File)=>void }) {
  const nav = [["overview","Overview"],["decision-analytics","Decision Analytics"],["feedback-details","Feedback Details"],["department-performance","Department Performance"]];
  return <div className="shell"><aside><div className="brand"><span>✦</span><div><b>FeedbackIQ</b><small>Intelligence dashboard</small></div></div><nav>{nav.map(([key,label]) => <button className={path===key?"active":""} onClick={()=>onNavigate(key)} key={key}>{label}</button>)}</nav><div className="side-bottom"><span className={online?"dot online":"dot"} />{online ? "System online" : "Backend offline"}</div></aside><main><header><div><p className="eyebrow">FEEDBACK INTELLIGENCE</p><h1>{nav.find(([key])=>key===path)?.[1] || "Overview"}</h1><p className="subtitle">{hasData ? "Live analysis from your backend dataset" : "Upload an analyzed feedback dataset to begin"}</p></div><label className="upload">Upload dataset<input type="file" accept=".csv,.xlsx,.xlsm" onChange={e=>e.target.files?.[0] && onUpload(e.target.files[0])}/></label></header>{children}</main></div>;
}
export function RecordsTable({ rows, onSelect }: { rows: FeedbackRecord[]; onSelect: (r: FeedbackRecord)=>void }) { return <div className="card table-wrap"><table><thead><tr>{["ID","Date","Feedback","Sentiment","Severity","Priority","Category / Department","Action"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} onClick={()=>onSelect(row)}><td>{text(row.feedback_id || row.id) || `Row ${i+1}`}</td><td>{text(row.date || row.created_at) || "—"}</td><td className="feedback">{text(row.feedback || row.cleaned_text)}</td><td>{text(row.sentiment) || "—"}</td><td><Badge value={text(row.severity)}/></td><td><Badge value={text(row.priority)}/></td><td>{categoryKey(row)}</td><td>{text(row.action) || "—"}</td></tr>)}</tbody></table>{!rows.length && <Empty text="No feedback found" />}</div>; }
export function Badge({ value }: { value: string }) { return <span className={`badge ${value.toLowerCase().replace(/[^a-z]/g,"-")}`}>{value || "Unknown"}</span>; }
export function Detail({ row, close }: { row: FeedbackRecord; close:()=>void }) { const groups = [["AI Analysis",["sentiment","sentiment_score","sentiment_confidence","emotion","topics","keywords","aspect_sentiments"]],["LangGraph Decision",["severity","severity_reason","priority","priority_reason","department","category","impact_level","action","action_reason"]],["Gemini Recommendation",["recommendation","recommendation_reason","suggested_next_step","recommendation_status"]]]; return <div className="overlay" onClick={close}><section className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">FEEDBACK DETAIL</p><h2>{text(row.feedback_id || row.id) || "Selected feedback"}</h2><p className="detail-feedback">{text(row.feedback || row.cleaned_text)}</p>{groups.map(([title, keys])=><div className="detail-group" key={title as string}><h3>{title}</h3>{(keys as string[]).filter(key=>row[key] !== undefined && row[key] !== null && row[key] !== "").map(key=><div className="detail-line" key={key}><span>{key.replaceAll("_"," ")}</span><b>{text(row[key])}</b></div>)}</div>)}</section></div>; }
export const metrics = (rows: FeedbackRecord[]) => { const categories = Object.entries(countBy(rows,"category")).length ? countBy(rows,"category") : rows.reduce<Record<string,number>>((o,r)=>{const k=categoryKey(r);o[k]=(o[k]||0)+1;return o;},{}); const high = rows.filter(r=>["HIGH","CRITICAL"].includes(text(r.severity))).length; const actions = rows.filter(r=>["CREATE_TASK","ESCALATE","IMMEDIATE_ESCALATION"].includes(text(r.action))).length; const avg = rows.length ? rows.reduce((s,r)=>s+priorityScore(r.priority),0)/rows.length : 0; return { severity: countBy(rows,"severity"), priority: countBy(rows,"priority"), action: countBy(rows,"action"), impact: countBy(rows,"impact_level"), category: categories, high, actions, avg }; };
